<?php


namespace calderawp\caldera\Forms;

use calderawp\caldera\Forms\Traits\PreparesFieldsFromArray;
use calderawp\caldera\Forms\Contracts\FormModelContract;
use calderawp\interop\Caldera;
use calderawp\interop\Contracts\Interoperable;
use calderawp\interop\Contracts\Rest\RestResponseContract;
use calderawp\interop\Traits\CalderaForms\ProvidesFields;
use calderawp\interop\Traits\CalderaForms\ProvidesForm;

class FormModel extends Caldera implements FormModelContract
{
	use ProvidesForm, ProvidesFields, PreparesFieldsFromArray;


	/**
	 * @param array $items
	 *
	 * @return FormModel
	 */
	public static function fromArray(array $items): Interoperable
	{

		$items = self::prepareFieldsFromArray($items);
		$obj = parent::fromArray($items);
		if (isset($items['fields'])&&is_object($items['fields'])) {
			$obj->setFields($items['fields']);
		}
		return $obj;
	}


	public function toResponse(int $statusCode = 200): RestResponseContract
	{
		return parent::toResponse($statusCode); // TODO: Change the autogenerated stub
	}
}
